/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FCMAgentRegistryInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_ROLE" | "AGENT_ROLE" | "DEFAULT_ADMIN_ROLE" | "HEARTBEAT_INTERVAL" | "MIN_STAKE" | "SLASH_PERCENT" | "VALIDATOR_ROLE" | "agentList" | "agents" | "calculateReward" | "cancelTask" | "claimExpiredDispute" | "claimTask" | "createTask" | "disputeResolutionDeadline" | "disputeTask" | "disputeWindow" | "fcmToken" | "getAgentOperator" | "getAgentStatus" | "getAgentsByType" | "getRoleAdmin" | "grantRole" | "hasRole" | "heartbeat" | "operatorActiveTasks" | "operatorAgents" | "pause" | "paused" | "registerAgent" | "renounceRole" | "resolveDispute" | "revokeRole" | "setDisputeResolutionDeadline" | "setDisputeWindow" | "slashHistory" | "submitResult" | "supportsInterface" | "taskList" | "tasks" | "unpause" | "unstake" | "withdrawReward"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentRegistered" | "AgentReregistered" | "AgentSlashed" | "AgentUpdated" | "DisputeExpired" | "DisputeWindowUpdated" | "Heartbeat" | "Paused" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "TaskAssigned" | "TaskCancelled" | "TaskCompleted" | "TaskCreated" | "TaskDisputed" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'AGENT_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'HEARTBEAT_INTERVAL', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_STAKE', values?: undefined): string;
encodeFunctionData(functionFragment: 'SLASH_PERCENT', values?: undefined): string;
encodeFunctionData(functionFragment: 'VALIDATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'agentList', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'agents', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'calculateReward', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'cancelTask', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'claimExpiredDispute', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'claimTask', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'createTask', values: [BytesLike, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'disputeResolutionDeadline', values?: undefined): string;
encodeFunctionData(functionFragment: 'disputeTask', values: [BytesLike, string]): string;
encodeFunctionData(functionFragment: 'disputeWindow', values?: undefined): string;
encodeFunctionData(functionFragment: 'fcmToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAgentOperator', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getAgentStatus', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getAgentsByType', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'heartbeat', values: [BytesLike, BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'operatorActiveTasks', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'operatorAgents', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerAgent', values: [BytesLike, string, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BytesLike, boolean, string]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setDisputeResolutionDeadline', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDisputeWindow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'slashHistory', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'submitResult', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'taskList', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tasks', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'unstake', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'withdrawReward', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'AGENT_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'HEARTBEAT_INTERVAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_STAKE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SLASH_PERCENT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VALIDATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agentList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimExpiredDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeResolutionDeadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fcmToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentsByType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'heartbeat', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operatorActiveTasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operatorAgents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDisputeResolutionDeadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDisputeWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slashHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitResult', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'taskList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawReward', data: BytesLike): Result;
  }

  
    export namespace AgentRegisteredEvent {
      export type InputTuple = [didHash: BytesLike, operator: AddressLike, agentType: BigNumberish, geohash: BytesLike];
      export type OutputTuple = [didHash: string, operator: string, agentType: bigint, geohash: string];
      export interface OutputObject {didHash: string, operator: string, agentType: bigint, geohash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentReregisteredEvent {
      export type InputTuple = [didHash: BytesLike, operator: AddressLike, agentType: BigNumberish];
      export type OutputTuple = [didHash: string, operator: string, agentType: bigint];
      export interface OutputObject {didHash: string, operator: string, agentType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentSlashedEvent {
      export type InputTuple = [didHash: BytesLike, amount: BigNumberish, reason: string];
      export type OutputTuple = [didHash: string, amount: bigint, reason: string];
      export interface OutputObject {didHash: string, amount: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentUpdatedEvent {
      export type InputTuple = [didHash: BytesLike, reputation: BigNumberish, isActive: boolean];
      export type OutputTuple = [didHash: string, reputation: bigint, isActive: boolean];
      export interface OutputObject {didHash: string, reputation: bigint, isActive: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeExpiredEvent {
      export type InputTuple = [taskId: BytesLike, claimant: AddressLike, refund: BigNumberish];
      export type OutputTuple = [taskId: string, claimant: string, refund: bigint];
      export interface OutputObject {taskId: string, claimant: string, refund: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeWindowUpdatedEvent {
      export type InputTuple = [oldWindow: BigNumberish, newWindow: BigNumberish];
      export type OutputTuple = [oldWindow: bigint, newWindow: bigint];
      export interface OutputObject {oldWindow: bigint, newWindow: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HeartbeatEvent {
      export type InputTuple = [didHash: BytesLike, timestamp: BigNumberish, geohash: BytesLike];
      export type OutputTuple = [didHash: string, timestamp: bigint, geohash: string];
      export interface OutputObject {didHash: string, timestamp: bigint, geohash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskAssignedEvent {
      export type InputTuple = [taskId: BytesLike, agentDid: BytesLike];
      export type OutputTuple = [taskId: string, agentDid: string];
      export interface OutputObject {taskId: string, agentDid: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCancelledEvent {
      export type InputTuple = [taskId: BytesLike, requester: AddressLike, refund: BigNumberish];
      export type OutputTuple = [taskId: string, requester: string, refund: bigint];
      export interface OutputObject {taskId: string, requester: string, refund: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCompletedEvent {
      export type InputTuple = [taskId: BytesLike, outputCID: BytesLike, proofHash: BytesLike];
      export type OutputTuple = [taskId: string, outputCID: string, proofHash: string];
      export interface OutputObject {taskId: string, outputCID: string, proofHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskCreatedEvent {
      export type InputTuple = [taskId: BytesLike, requester: AddressLike, reward: BigNumberish];
      export type OutputTuple = [taskId: string, requester: string, reward: bigint];
      export interface OutputObject {taskId: string, requester: string, reward: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskDisputedEvent {
      export type InputTuple = [taskId: BytesLike, disputant: AddressLike, reason: string];
      export type OutputTuple = [taskId: string, disputant: string, reason: string];
      export interface OutputObject {taskId: string, disputant: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FCMAgentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): FCMAgentRegistry;
    waitForDeployment(): Promise<this>;

    interface: FCMAgentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    AGENT_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    HEARTBEAT_INTERVAL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_STAKE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SLASH_PERCENT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    VALIDATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    agentList: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    agents: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, string, bigint, bigint, bigint, bigint, string, string, boolean, bigint, bigint] & {didHash: string, ipnsRecord: string, operator: string, stake: bigint, reputation: bigint, registeredAt: bigint, lastHeartbeat: bigint, capabilities: string, geohash: string, isActive: boolean, agentType: bigint, heartbeatNonce: bigint }],
      'view'
    >
    

    
    calculateReward: TypedContractMethod<
      [_requirements: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    cancelTask: TypedContractMethod<
      [_taskId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    claimExpiredDispute: TypedContractMethod<
      [_taskId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    claimTask: TypedContractMethod<
      [_taskId: BytesLike, _didHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    createTask: TypedContractMethod<
      [_taskId: BytesLike, _requirements: BytesLike, _inputCID: BytesLike, _deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    disputeResolutionDeadline: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    disputeTask: TypedContractMethod<
      [_taskId: BytesLike, _reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    disputeWindow: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fcmToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAgentOperator: TypedContractMethod<
      [_didHash: BytesLike, ],
      [string],
      'view'
    >
    

    
    getAgentStatus: TypedContractMethod<
      [_didHash: BytesLike, ],
      [[boolean, string] & {isActive: boolean, operator: string }],
      'view'
    >
    

    
    getAgentsByType: TypedContractMethod<
      [_agentType: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    heartbeat: TypedContractMethod<
      [_didHash: BytesLike, _geohash: BytesLike, _nonce: BigNumberish, _signature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    operatorActiveTasks: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    operatorAgents: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    registerAgent: TypedContractMethod<
      [_didHash: BytesLike, _ipnsRecord: string, _capabilities: BytesLike, _geohash: BytesLike, _agentType: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [_taskId: BytesLike, _agentFault: boolean, _resolution: string, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setDisputeResolutionDeadline: TypedContractMethod<
      [_deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setDisputeWindow: TypedContractMethod<
      [_window: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    slashHistory: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    submitResult: TypedContractMethod<
      [_taskId: BytesLike, _outputCID: BytesLike, _proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    taskList: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    tasks: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, string, string, string, string, bigint, string, boolean, bigint, string] & {taskId: string, requester: string, reward: bigint, deadline: bigint, requirements: string, inputCID: string, outputCID: string, assignedAgent: string, status: bigint, proofHash: string, rewardWithdrawn: boolean, disputedAt: bigint, assignedDid: string }],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    unstake: TypedContractMethod<
      [_didHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawReward: TypedContractMethod<
      [_taskId: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'AGENT_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'HEARTBEAT_INTERVAL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_STAKE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SLASH_PERCENT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'VALIDATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'agentList'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'agents'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, string, bigint, bigint, bigint, bigint, string, string, boolean, bigint, bigint] & {didHash: string, ipnsRecord: string, operator: string, stake: bigint, reputation: bigint, registeredAt: bigint, lastHeartbeat: bigint, capabilities: string, geohash: string, isActive: boolean, agentType: bigint, heartbeatNonce: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'calculateReward'): TypedContractMethod<
      [_requirements: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelTask'): TypedContractMethod<
      [_taskId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimExpiredDispute'): TypedContractMethod<
      [_taskId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimTask'): TypedContractMethod<
      [_taskId: BytesLike, _didHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createTask'): TypedContractMethod<
      [_taskId: BytesLike, _requirements: BytesLike, _inputCID: BytesLike, _deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disputeResolutionDeadline'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'disputeTask'): TypedContractMethod<
      [_taskId: BytesLike, _reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disputeWindow'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fcmToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentOperator'): TypedContractMethod<
      [_didHash: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentStatus'): TypedContractMethod<
      [_didHash: BytesLike, ],
      [[boolean, string] & {isActive: boolean, operator: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentsByType'): TypedContractMethod<
      [_agentType: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'heartbeat'): TypedContractMethod<
      [_didHash: BytesLike, _geohash: BytesLike, _nonce: BigNumberish, _signature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'operatorActiveTasks'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'operatorAgents'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerAgent'): TypedContractMethod<
      [_didHash: BytesLike, _ipnsRecord: string, _capabilities: BytesLike, _geohash: BytesLike, _agentType: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [_taskId: BytesLike, _agentFault: boolean, _resolution: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDisputeResolutionDeadline'): TypedContractMethod<
      [_deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDisputeWindow'): TypedContractMethod<
      [_window: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'slashHistory'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submitResult'): TypedContractMethod<
      [_taskId: BytesLike, _outputCID: BytesLike, _proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'taskList'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tasks'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, string, string, string, string, bigint, string, boolean, bigint, string] & {taskId: string, requester: string, reward: bigint, deadline: bigint, requirements: string, inputCID: string, outputCID: string, assignedAgent: string, status: bigint, proofHash: string, rewardWithdrawn: boolean, disputedAt: bigint, assignedDid: string }],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unstake'): TypedContractMethod<
      [_didHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawReward'): TypedContractMethod<
      [_taskId: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgentRegistered'): TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
getEvent(key: 'AgentReregistered'): TypedContractEvent<AgentReregisteredEvent.InputTuple, AgentReregisteredEvent.OutputTuple, AgentReregisteredEvent.OutputObject>;
getEvent(key: 'AgentSlashed'): TypedContractEvent<AgentSlashedEvent.InputTuple, AgentSlashedEvent.OutputTuple, AgentSlashedEvent.OutputObject>;
getEvent(key: 'AgentUpdated'): TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
getEvent(key: 'DisputeExpired'): TypedContractEvent<DisputeExpiredEvent.InputTuple, DisputeExpiredEvent.OutputTuple, DisputeExpiredEvent.OutputObject>;
getEvent(key: 'DisputeWindowUpdated'): TypedContractEvent<DisputeWindowUpdatedEvent.InputTuple, DisputeWindowUpdatedEvent.OutputTuple, DisputeWindowUpdatedEvent.OutputObject>;
getEvent(key: 'Heartbeat'): TypedContractEvent<HeartbeatEvent.InputTuple, HeartbeatEvent.OutputTuple, HeartbeatEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'TaskAssigned'): TypedContractEvent<TaskAssignedEvent.InputTuple, TaskAssignedEvent.OutputTuple, TaskAssignedEvent.OutputObject>;
getEvent(key: 'TaskCancelled'): TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
getEvent(key: 'TaskCompleted'): TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
getEvent(key: 'TaskCreated'): TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
getEvent(key: 'TaskDisputed'): TypedContractEvent<TaskDisputedEvent.InputTuple, TaskDisputedEvent.OutputTuple, TaskDisputedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'AgentRegistered(bytes32,address,uint8,bytes32)': TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
      AgentRegistered: TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
    

      'AgentReregistered(bytes32,address,uint8)': TypedContractEvent<AgentReregisteredEvent.InputTuple, AgentReregisteredEvent.OutputTuple, AgentReregisteredEvent.OutputObject>;
      AgentReregistered: TypedContractEvent<AgentReregisteredEvent.InputTuple, AgentReregisteredEvent.OutputTuple, AgentReregisteredEvent.OutputObject>;
    

      'AgentSlashed(bytes32,uint256,string)': TypedContractEvent<AgentSlashedEvent.InputTuple, AgentSlashedEvent.OutputTuple, AgentSlashedEvent.OutputObject>;
      AgentSlashed: TypedContractEvent<AgentSlashedEvent.InputTuple, AgentSlashedEvent.OutputTuple, AgentSlashedEvent.OutputObject>;
    

      'AgentUpdated(bytes32,uint256,bool)': TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
      AgentUpdated: TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
    

      'DisputeExpired(bytes32,address,uint256)': TypedContractEvent<DisputeExpiredEvent.InputTuple, DisputeExpiredEvent.OutputTuple, DisputeExpiredEvent.OutputObject>;
      DisputeExpired: TypedContractEvent<DisputeExpiredEvent.InputTuple, DisputeExpiredEvent.OutputTuple, DisputeExpiredEvent.OutputObject>;
    

      'DisputeWindowUpdated(uint256,uint256)': TypedContractEvent<DisputeWindowUpdatedEvent.InputTuple, DisputeWindowUpdatedEvent.OutputTuple, DisputeWindowUpdatedEvent.OutputObject>;
      DisputeWindowUpdated: TypedContractEvent<DisputeWindowUpdatedEvent.InputTuple, DisputeWindowUpdatedEvent.OutputTuple, DisputeWindowUpdatedEvent.OutputObject>;
    

      'Heartbeat(bytes32,uint256,bytes32)': TypedContractEvent<HeartbeatEvent.InputTuple, HeartbeatEvent.OutputTuple, HeartbeatEvent.OutputObject>;
      Heartbeat: TypedContractEvent<HeartbeatEvent.InputTuple, HeartbeatEvent.OutputTuple, HeartbeatEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'TaskAssigned(bytes32,bytes32)': TypedContractEvent<TaskAssignedEvent.InputTuple, TaskAssignedEvent.OutputTuple, TaskAssignedEvent.OutputObject>;
      TaskAssigned: TypedContractEvent<TaskAssignedEvent.InputTuple, TaskAssignedEvent.OutputTuple, TaskAssignedEvent.OutputObject>;
    

      'TaskCancelled(bytes32,address,uint256)': TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
      TaskCancelled: TypedContractEvent<TaskCancelledEvent.InputTuple, TaskCancelledEvent.OutputTuple, TaskCancelledEvent.OutputObject>;
    

      'TaskCompleted(bytes32,bytes32,bytes32)': TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
      TaskCompleted: TypedContractEvent<TaskCompletedEvent.InputTuple, TaskCompletedEvent.OutputTuple, TaskCompletedEvent.OutputObject>;
    

      'TaskCreated(bytes32,address,uint256)': TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
      TaskCreated: TypedContractEvent<TaskCreatedEvent.InputTuple, TaskCreatedEvent.OutputTuple, TaskCreatedEvent.OutputObject>;
    

      'TaskDisputed(bytes32,address,string)': TypedContractEvent<TaskDisputedEvent.InputTuple, TaskDisputedEvent.OutputTuple, TaskDisputedEvent.OutputObject>;
      TaskDisputed: TypedContractEvent<TaskDisputedEvent.InputTuple, TaskDisputedEvent.OutputTuple, TaskDisputedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }