/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FCMEscrowInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_ROLE" | "ARBITRATOR_ROLE" | "DEFAULT_ADMIN_ROLE" | "approveMilestone" | "cancelEscrow" | "clientEscrows" | "createEscrow" | "disputeMilestone" | "disputeWindow" | "escrowCount" | "escrows" | "fcmToken" | "fundEscrow" | "getEscrowMilestones" | "getEscrowSummary" | "getRoleAdmin" | "grantRole" | "hasRole" | "maxMilestones" | "multisigThreshold" | "paused" | "renounceRole" | "resolveDispute" | "revokeRole" | "setMultisigThreshold" | "submitMilestone" | "supportsInterface" | "workerEscrows"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeResolved" | "EscrowCancelled" | "EscrowCreated" | "EscrowFunded" | "FundsReleased" | "MilestoneApproved" | "MilestoneDisputed" | "MilestoneSubmitted" | "Paused" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ARBITRATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveMilestone', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelEscrow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'clientEscrows', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createEscrow', values: [AddressLike, string[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'disputeMilestone', values: [BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'disputeWindow', values?: undefined): string;
encodeFunctionData(functionFragment: 'escrowCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'escrows', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fcmToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundEscrow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEscrowMilestones', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEscrowSummary', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'maxMilestones', values?: undefined): string;
encodeFunctionData(functionFragment: 'multisigThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, boolean, string]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setMultisigThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitMilestone', values: [BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'workerEscrows', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ARBITRATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'clientEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fcmToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEscrowMilestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEscrowSummary', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxMilestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'multisigThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMultisigThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'workerEscrows', data: BytesLike): Result;
  }

  
    export namespace DisputeResolvedEvent {
      export type InputTuple = [id: BigNumberish, clientWins: boolean, amount: BigNumberish, resolution: string];
      export type OutputTuple = [id: bigint, clientWins: boolean, amount: bigint, resolution: string];
      export interface OutputObject {id: bigint, clientWins: boolean, amount: bigint, resolution: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowCancelledEvent {
      export type InputTuple = [id: BigNumberish, refund: BigNumberish];
      export type OutputTuple = [id: bigint, refund: bigint];
      export interface OutputObject {id: bigint, refund: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowCreatedEvent {
      export type InputTuple = [id: BigNumberish, client: AddressLike, worker: AddressLike, totalAmount: BigNumberish, milestoneCount: BigNumberish];
      export type OutputTuple = [id: bigint, client: string, worker: string, totalAmount: bigint, milestoneCount: bigint];
      export interface OutputObject {id: bigint, client: string, worker: string, totalAmount: bigint, milestoneCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowFundedEvent {
      export type InputTuple = [id: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [id: bigint, amount: bigint];
      export interface OutputObject {id: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsReleasedEvent {
      export type InputTuple = [id: BigNumberish, amount: BigNumberish, to: AddressLike];
      export type OutputTuple = [id: bigint, amount: bigint, to: string];
      export interface OutputObject {id: bigint, amount: bigint, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneApprovedEvent {
      export type InputTuple = [id: BigNumberish, milestoneIndex: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [id: bigint, milestoneIndex: bigint, amount: bigint];
      export interface OutputObject {id: bigint, milestoneIndex: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneDisputedEvent {
      export type InputTuple = [id: BigNumberish, milestoneIndex: BigNumberish, reason: string];
      export type OutputTuple = [id: bigint, milestoneIndex: bigint, reason: string];
      export interface OutputObject {id: bigint, milestoneIndex: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneSubmittedEvent {
      export type InputTuple = [id: BigNumberish, milestoneIndex: BigNumberish, deliverableCID: BytesLike];
      export type OutputTuple = [id: bigint, milestoneIndex: bigint, deliverableCID: string];
      export interface OutputObject {id: bigint, milestoneIndex: bigint, deliverableCID: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FCMEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): FCMEscrow;
    waitForDeployment(): Promise<this>;

    interface: FCMEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ARBITRATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    approveMilestone: TypedContractMethod<
      [escrowId: BigNumberish, milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelEscrow: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    clientEscrows: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    createEscrow: TypedContractMethod<
      [worker: AddressLike, milestoneDescriptions: string[], milestoneAmounts: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >
    

    
    disputeMilestone: TypedContractMethod<
      [escrowId: BigNumberish, milestoneIndex: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    disputeWindow: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    escrowCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    escrows: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {id: bigint, client: string, worker: string, totalAmount: bigint, releasedAmount: bigint, remainingAmount: bigint, createdAt: bigint, deadline: bigint, disputeDeadline: bigint, state: bigint, completedMilestones: bigint, requiresMultiSig: boolean, approvalCount: bigint }],
      'view'
    >
    

    
    fcmToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    fundEscrow: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getEscrowMilestones: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [[string[], bigint[], boolean[], boolean[]] & {descriptions: string[], amounts: bigint[], approved: boolean[], submitted: boolean[] }],
      'view'
    >
    

    
    getEscrowSummary: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint] & {client: string, worker: string, totalAmount: bigint, releasedAmount: bigint, completedMilestones: bigint, totalMilestones: bigint, state: bigint }],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    maxMilestones: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    multisigThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [escrowId: BigNumberish, clientWins: boolean, resolution: string, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMultisigThreshold: TypedContractMethod<
      [_threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitMilestone: TypedContractMethod<
      [escrowId: BigNumberish, milestoneIndex: BigNumberish, deliverableCID: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    workerEscrows: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ARBITRATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'approveMilestone'): TypedContractMethod<
      [escrowId: BigNumberish, milestoneIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelEscrow'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'clientEscrows'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [worker: AddressLike, milestoneDescriptions: string[], milestoneAmounts: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disputeMilestone'): TypedContractMethod<
      [escrowId: BigNumberish, milestoneIndex: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'disputeWindow'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'escrowCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'escrows'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {id: bigint, client: string, worker: string, totalAmount: bigint, releasedAmount: bigint, remainingAmount: bigint, createdAt: bigint, deadline: bigint, disputeDeadline: bigint, state: bigint, completedMilestones: bigint, requiresMultiSig: boolean, approvalCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'fcmToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fundEscrow'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getEscrowMilestones'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [[string[], bigint[], boolean[], boolean[]] & {descriptions: string[], amounts: bigint[], approved: boolean[], submitted: boolean[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getEscrowSummary'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint] & {client: string, worker: string, totalAmount: bigint, releasedAmount: bigint, completedMilestones: bigint, totalMilestones: bigint, state: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'maxMilestones'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'multisigThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [escrowId: BigNumberish, clientWins: boolean, resolution: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMultisigThreshold'): TypedContractMethod<
      [_threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitMilestone'): TypedContractMethod<
      [escrowId: BigNumberish, milestoneIndex: BigNumberish, deliverableCID: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'workerEscrows'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'EscrowCancelled'): TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'EscrowFunded'): TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
getEvent(key: 'FundsReleased'): TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
getEvent(key: 'MilestoneApproved'): TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
getEvent(key: 'MilestoneDisputed'): TypedContractEvent<MilestoneDisputedEvent.InputTuple, MilestoneDisputedEvent.OutputTuple, MilestoneDisputedEvent.OutputObject>;
getEvent(key: 'MilestoneSubmitted'): TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'DisputeResolved(uint256,bool,uint256,string)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'EscrowCancelled(uint256,uint256)': TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
      EscrowCancelled: TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
    

      'EscrowCreated(uint256,address,address,uint256,uint256)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'EscrowFunded(uint256,uint256)': TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
      EscrowFunded: TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
    

      'FundsReleased(uint256,uint256,address)': TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
      FundsReleased: TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
    

      'MilestoneApproved(uint256,uint256,uint256)': TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
      MilestoneApproved: TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
    

      'MilestoneDisputed(uint256,uint256,string)': TypedContractEvent<MilestoneDisputedEvent.InputTuple, MilestoneDisputedEvent.OutputTuple, MilestoneDisputedEvent.OutputObject>;
      MilestoneDisputed: TypedContractEvent<MilestoneDisputedEvent.InputTuple, MilestoneDisputedEvent.OutputTuple, MilestoneDisputedEvent.OutputObject>;
    

      'MilestoneSubmitted(uint256,uint256,bytes32)': TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
      MilestoneSubmitted: TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }