/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace FCMReputationNFT {
      
    export type BadgeStruct = {operator: AddressLike, didHash: BytesLike, tier: BigNumberish, totalWork: BigNumberish, totalEarnings: BigNumberish, uptimeScore: BigNumberish, disputesWon: BigNumberish, disputesLost: BigNumberish, consecutiveDays: BigNumberish, mintedAt: BigNumberish, lastUpdated: BigNumberish, exists: boolean}

    export type BadgeStructOutput = [operator: string, didHash: string, tier: bigint, totalWork: bigint, totalEarnings: bigint, uptimeScore: bigint, disputesWon: bigint, disputesLost: bigint, consecutiveDays: bigint, mintedAt: bigint, lastUpdated: bigint, exists: boolean] & {operator: string, didHash: string, tier: bigint, totalWork: bigint, totalEarnings: bigint, uptimeScore: bigint, disputesWon: bigint, disputesLost: bigint, consecutiveDays: bigint, mintedAt: bigint, lastUpdated: bigint, exists: boolean }
  
    }

  export interface FCMReputationNFTInterface extends Interface {
    getFunction(nameOrSignature: "ACHIEVEMENT_1000_TASKS" | "ACHIEVEMENT_100_TASKS" | "ACHIEVEMENT_DISPUTE_CHAMPION" | "ACHIEVEMENT_FIRST_TASK" | "ACHIEVEMENT_MILLION_EARNED" | "ACHIEVEMENT_PERFECT_UPTIME" | "ACHIEVEMENT_TIER_5" | "ACHIEVEMENT_YEAR_VETERAN" | "ADMIN_ROLE" | "DEFAULT_ADMIN_ROLE" | "ORACLE_ROLE" | "achievements" | "approve" | "badges" | "balanceOf" | "didBadge" | "getAchievements" | "getApproved" | "getBadge" | "getRoleAdmin" | "grantRole" | "hasAchievement" | "hasRole" | "incrementStreak" | "isApprovedForAll" | "mintBadge" | "name" | "operatorBadge" | "ownerOf" | "paused" | "renounceRole" | "revokeBadge" | "revokeRole" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "setApprovalForAll" | "supportsInterface" | "symbol" | "tokenURI" | "totalSupply" | "transferFrom" | "updateBadge"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AchievementUnlocked" | "Approval" | "ApprovalForAll" | "BadgeMinted" | "BadgeUpdated" | "Paused" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Transfer" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'ACHIEVEMENT_1000_TASKS', values?: undefined): string;
encodeFunctionData(functionFragment: 'ACHIEVEMENT_100_TASKS', values?: undefined): string;
encodeFunctionData(functionFragment: 'ACHIEVEMENT_DISPUTE_CHAMPION', values?: undefined): string;
encodeFunctionData(functionFragment: 'ACHIEVEMENT_FIRST_TASK', values?: undefined): string;
encodeFunctionData(functionFragment: 'ACHIEVEMENT_MILLION_EARNED', values?: undefined): string;
encodeFunctionData(functionFragment: 'ACHIEVEMENT_PERFECT_UPTIME', values?: undefined): string;
encodeFunctionData(functionFragment: 'ACHIEVEMENT_TIER_5', values?: undefined): string;
encodeFunctionData(functionFragment: 'ACHIEVEMENT_YEAR_VETERAN', values?: undefined): string;
encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ORACLE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'achievements', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'badges', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'didBadge', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getAchievements', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBadge', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasAchievement', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'incrementStreak', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'mintBadge', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'operatorBadge', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeBadge', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateBadge', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean, boolean]): string;

    decodeFunctionResult(functionFragment: 'ACHIEVEMENT_1000_TASKS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ACHIEVEMENT_100_TASKS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ACHIEVEMENT_DISPUTE_CHAMPION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ACHIEVEMENT_FIRST_TASK', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ACHIEVEMENT_MILLION_EARNED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ACHIEVEMENT_PERFECT_UPTIME', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ACHIEVEMENT_TIER_5', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ACHIEVEMENT_YEAR_VETERAN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ORACLE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'achievements', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'badges', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'didBadge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAchievements', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBadge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasAchievement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'incrementStreak', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintBadge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operatorBadge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeBadge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateBadge', data: BytesLike): Result;
  }

  
    export namespace AchievementUnlockedEvent {
      export type InputTuple = [tokenId: BigNumberish, achievement: BigNumberish];
      export type OutputTuple = [tokenId: bigint, achievement: bigint];
      export interface OutputObject {tokenId: bigint, achievement: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BadgeMintedEvent {
      export type InputTuple = [tokenId: BigNumberish, operator: AddressLike, didHash: BytesLike];
      export type OutputTuple = [tokenId: bigint, operator: string, didHash: string];
      export interface OutputObject {tokenId: bigint, operator: string, didHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BadgeUpdatedEvent {
      export type InputTuple = [tokenId: BigNumberish, newTier: BigNumberish, totalWork: BigNumberish];
      export type OutputTuple = [tokenId: bigint, newTier: bigint, totalWork: bigint];
      export interface OutputObject {tokenId: bigint, newTier: bigint, totalWork: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FCMReputationNFT extends BaseContract {
    
    connect(runner?: ContractRunner | null): FCMReputationNFT;
    waitForDeployment(): Promise<this>;

    interface: FCMReputationNFTInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ACHIEVEMENT_1000_TASKS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ACHIEVEMENT_100_TASKS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ACHIEVEMENT_DISPUTE_CHAMPION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ACHIEVEMENT_FIRST_TASK: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ACHIEVEMENT_MILLION_EARNED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ACHIEVEMENT_PERFECT_UPTIME: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ACHIEVEMENT_TIER_5: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ACHIEVEMENT_YEAR_VETERAN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ORACLE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    achievements: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [void],
      'view'
    >
    

    
    badges: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {operator: string, didHash: string, tier: bigint, totalWork: bigint, totalEarnings: bigint, uptimeScore: bigint, disputesWon: bigint, disputesLost: bigint, consecutiveDays: bigint, mintedAt: bigint, lastUpdated: bigint, exists: boolean }],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    didBadge: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getAchievements: TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getBadge: TypedContractMethod<
      [operator: AddressLike, ],
      [FCMReputationNFT.BadgeStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasAchievement: TypedContractMethod<
      [operator: AddressLike, achievement: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    incrementStreak: TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    mintBadge: TypedContractMethod<
      [operator: AddressLike, didHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    operatorBadge: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeBadge: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, ],
      [void],
      'view'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [void],
      'view'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [arg0: AddressLike, arg1: boolean, ],
      [void],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, ],
      [void],
      'view'
    >
    

    
    updateBadge: TypedContractMethod<
      [operator: AddressLike, newTier: BigNumberish, addWork: BigNumberish, addEarnings: BigNumberish, newUptime: BigNumberish, disputeWon: boolean, disputeLost: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ACHIEVEMENT_1000_TASKS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ACHIEVEMENT_100_TASKS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ACHIEVEMENT_DISPUTE_CHAMPION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ACHIEVEMENT_FIRST_TASK'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ACHIEVEMENT_MILLION_EARNED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ACHIEVEMENT_PERFECT_UPTIME'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ACHIEVEMENT_TIER_5'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ACHIEVEMENT_YEAR_VETERAN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ORACLE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'achievements'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'badges'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {operator: string, didHash: string, tier: bigint, totalWork: bigint, totalEarnings: bigint, uptimeScore: bigint, disputesWon: bigint, disputesLost: bigint, consecutiveDays: bigint, mintedAt: bigint, lastUpdated: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'didBadge'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAchievements'): TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getBadge'): TypedContractMethod<
      [operator: AddressLike, ],
      [FCMReputationNFT.BadgeStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasAchievement'): TypedContractMethod<
      [operator: AddressLike, achievement: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'incrementStreak'): TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mintBadge'): TypedContractMethod<
      [operator: AddressLike, didHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'operatorBadge'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeBadge'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [arg0: AddressLike, arg1: boolean, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'updateBadge'): TypedContractMethod<
      [operator: AddressLike, newTier: BigNumberish, addWork: BigNumberish, addEarnings: BigNumberish, newUptime: BigNumberish, disputeWon: boolean, disputeLost: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AchievementUnlocked'): TypedContractEvent<AchievementUnlockedEvent.InputTuple, AchievementUnlockedEvent.OutputTuple, AchievementUnlockedEvent.OutputObject>;
getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'BadgeMinted'): TypedContractEvent<BadgeMintedEvent.InputTuple, BadgeMintedEvent.OutputTuple, BadgeMintedEvent.OutputObject>;
getEvent(key: 'BadgeUpdated'): TypedContractEvent<BadgeUpdatedEvent.InputTuple, BadgeUpdatedEvent.OutputTuple, BadgeUpdatedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'AchievementUnlocked(uint256,uint256)': TypedContractEvent<AchievementUnlockedEvent.InputTuple, AchievementUnlockedEvent.OutputTuple, AchievementUnlockedEvent.OutputObject>;
      AchievementUnlocked: TypedContractEvent<AchievementUnlockedEvent.InputTuple, AchievementUnlockedEvent.OutputTuple, AchievementUnlockedEvent.OutputObject>;
    

      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'BadgeMinted(uint256,address,bytes32)': TypedContractEvent<BadgeMintedEvent.InputTuple, BadgeMintedEvent.OutputTuple, BadgeMintedEvent.OutputObject>;
      BadgeMinted: TypedContractEvent<BadgeMintedEvent.InputTuple, BadgeMintedEvent.OutputTuple, BadgeMintedEvent.OutputObject>;
    

      'BadgeUpdated(uint256,uint8,uint256)': TypedContractEvent<BadgeUpdatedEvent.InputTuple, BadgeUpdatedEvent.OutputTuple, BadgeUpdatedEvent.OutputObject>;
      BadgeUpdated: TypedContractEvent<BadgeUpdatedEvent.InputTuple, BadgeUpdatedEvent.OutputTuple, BadgeUpdatedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }