/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FCMTierStakingInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_ROLE" | "DEFAULT_ADMIN_ROLE" | "HARDWARE_CHECK_INTERVAL" | "MAX_TIERS" | "ORACLE_ROLE" | "TIER_CHANGE_GRACE_PERIOD" | "applyPendingDowngrade" | "emergencyWithdraw" | "fcmToken" | "getEffectiveMultiplier" | "getFeeDiscount" | "getMaxConcurrent" | "getRoleAdmin" | "getStakedAmount" | "getStakerCount" | "getStakersByTier" | "getTier" | "grantRole" | "hasRole" | "paused" | "renounceRole" | "revokeRole" | "stake" | "stakers" | "stakes" | "supportsInterface" | "tierStakeCount" | "tiers" | "unstake" | "updateHardwareScore" | "updateTierConfig"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "HardwareScoreUpdated" | "Paused" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Staked" | "TierConfigUpdated" | "TierDowngraded" | "TierUpgraded" | "Unpaused" | "Unstaked"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'HARDWARE_CHECK_INTERVAL', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_TIERS', values?: undefined): string;
encodeFunctionData(functionFragment: 'ORACLE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'TIER_CHANGE_GRACE_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'applyPendingDowngrade', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values?: undefined): string;
encodeFunctionData(functionFragment: 'fcmToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'getEffectiveMultiplier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getFeeDiscount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMaxConcurrent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getStakedAmount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getStakerCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getStakersByTier', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakes', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'tierStakeCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tiers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'unstake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateHardwareScore', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateTierConfig', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'HARDWARE_CHECK_INTERVAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_TIERS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ORACLE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TIER_CHANGE_GRACE_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'applyPendingDowngrade', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fcmToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEffectiveMultiplier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFeeDiscount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMaxConcurrent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStakedAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStakerCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStakersByTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tierStakeCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tiers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateHardwareScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTierConfig', data: BytesLike): Result;
  }

  
    export namespace HardwareScoreUpdatedEvent {
      export type InputTuple = [operator: AddressLike, hardwareScore: BigNumberish, uptimeScore: BigNumberish];
      export type OutputTuple = [operator: string, hardwareScore: bigint, uptimeScore: bigint];
      export interface OutputObject {operator: string, hardwareScore: bigint, uptimeScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakedEvent {
      export type InputTuple = [operator: AddressLike, amount: BigNumberish, tier: BigNumberish];
      export type OutputTuple = [operator: string, amount: bigint, tier: bigint];
      export interface OutputObject {operator: string, amount: bigint, tier: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TierConfigUpdatedEvent {
      export type InputTuple = [tier: BigNumberish, name: string, minStake: BigNumberish, minScore: BigNumberish];
      export type OutputTuple = [tier: bigint, name: string, minStake: bigint, minScore: bigint];
      export interface OutputObject {tier: bigint, name: string, minStake: bigint, minScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TierDowngradedEvent {
      export type InputTuple = [operator: AddressLike, oldTier: BigNumberish, newTier: BigNumberish];
      export type OutputTuple = [operator: string, oldTier: bigint, newTier: bigint];
      export interface OutputObject {operator: string, oldTier: bigint, newTier: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TierUpgradedEvent {
      export type InputTuple = [operator: AddressLike, oldTier: BigNumberish, newTier: BigNumberish];
      export type OutputTuple = [operator: string, oldTier: bigint, newTier: bigint];
      export interface OutputObject {operator: string, oldTier: bigint, newTier: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakedEvent {
      export type InputTuple = [operator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [operator: string, amount: bigint];
      export interface OutputObject {operator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FCMTierStaking extends BaseContract {
    
    connect(runner?: ContractRunner | null): FCMTierStaking;
    waitForDeployment(): Promise<this>;

    interface: FCMTierStakingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    HARDWARE_CHECK_INTERVAL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_TIERS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ORACLE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    TIER_CHANGE_GRACE_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    applyPendingDowngrade: TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    fcmToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getEffectiveMultiplier: TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getFeeDiscount: TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getMaxConcurrent: TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getStakedAmount: TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getStakerCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getStakersByTier: TypedContractMethod<
      [tier: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getTier: TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    stake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakers: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    stakes: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {operator: string, amount: bigint, stakedAt: bigint, lastHardwareCheck: bigint, hardwareScore: bigint, uptimeScore: bigint, currentTier: bigint, targetTier: bigint, tierChangedAt: bigint, exists: boolean }],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    tierStakeCount: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    tiers: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, string] & {minStake: bigint, minScore: bigint, rewardMultiplier: bigint, feeDiscount: bigint, maxConcurrent: bigint, name: string }],
      'view'
    >
    

    
    unstake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateHardwareScore: TypedContractMethod<
      [operator: AddressLike, _hardwareScore: BigNumberish, _uptimeScore: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateTierConfig: TypedContractMethod<
      [_tier: BigNumberish, _minStake: BigNumberish, _minScore: BigNumberish, _rewardMultiplier: BigNumberish, _feeDiscount: BigNumberish, _maxConcurrent: BigNumberish, _name: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'HARDWARE_CHECK_INTERVAL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_TIERS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ORACLE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'TIER_CHANGE_GRACE_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'applyPendingDowngrade'): TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fcmToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getEffectiveMultiplier'): TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getFeeDiscount'): TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMaxConcurrent'): TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getStakedAmount'): TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getStakerCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getStakersByTier'): TypedContractMethod<
      [tier: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTier'): TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakers'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'stakes'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {operator: string, amount: bigint, stakedAt: bigint, lastHardwareCheck: bigint, hardwareScore: bigint, uptimeScore: bigint, currentTier: bigint, targetTier: bigint, tierChangedAt: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'tierStakeCount'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tiers'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, string] & {minStake: bigint, minScore: bigint, rewardMultiplier: bigint, feeDiscount: bigint, maxConcurrent: bigint, name: string }],
      'view'
    >;
getFunction(nameOrSignature: 'unstake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateHardwareScore'): TypedContractMethod<
      [operator: AddressLike, _hardwareScore: BigNumberish, _uptimeScore: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTierConfig'): TypedContractMethod<
      [_tier: BigNumberish, _minStake: BigNumberish, _minScore: BigNumberish, _rewardMultiplier: BigNumberish, _feeDiscount: BigNumberish, _maxConcurrent: BigNumberish, _name: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'HardwareScoreUpdated'): TypedContractEvent<HardwareScoreUpdatedEvent.InputTuple, HardwareScoreUpdatedEvent.OutputTuple, HardwareScoreUpdatedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Staked'): TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
getEvent(key: 'TierConfigUpdated'): TypedContractEvent<TierConfigUpdatedEvent.InputTuple, TierConfigUpdatedEvent.OutputTuple, TierConfigUpdatedEvent.OutputObject>;
getEvent(key: 'TierDowngraded'): TypedContractEvent<TierDowngradedEvent.InputTuple, TierDowngradedEvent.OutputTuple, TierDowngradedEvent.OutputObject>;
getEvent(key: 'TierUpgraded'): TypedContractEvent<TierUpgradedEvent.InputTuple, TierUpgradedEvent.OutputTuple, TierUpgradedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'Unstaked'): TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;

    filters: {
      
      'HardwareScoreUpdated(address,uint256,uint256)': TypedContractEvent<HardwareScoreUpdatedEvent.InputTuple, HardwareScoreUpdatedEvent.OutputTuple, HardwareScoreUpdatedEvent.OutputObject>;
      HardwareScoreUpdated: TypedContractEvent<HardwareScoreUpdatedEvent.InputTuple, HardwareScoreUpdatedEvent.OutputTuple, HardwareScoreUpdatedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Staked(address,uint256,uint8)': TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
      Staked: TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
    

      'TierConfigUpdated(uint8,string,uint256,uint256)': TypedContractEvent<TierConfigUpdatedEvent.InputTuple, TierConfigUpdatedEvent.OutputTuple, TierConfigUpdatedEvent.OutputObject>;
      TierConfigUpdated: TypedContractEvent<TierConfigUpdatedEvent.InputTuple, TierConfigUpdatedEvent.OutputTuple, TierConfigUpdatedEvent.OutputObject>;
    

      'TierDowngraded(address,uint8,uint8)': TypedContractEvent<TierDowngradedEvent.InputTuple, TierDowngradedEvent.OutputTuple, TierDowngradedEvent.OutputObject>;
      TierDowngraded: TypedContractEvent<TierDowngradedEvent.InputTuple, TierDowngradedEvent.OutputTuple, TierDowngradedEvent.OutputObject>;
    

      'TierUpgraded(address,uint8,uint8)': TypedContractEvent<TierUpgradedEvent.InputTuple, TierUpgradedEvent.OutputTuple, TierUpgradedEvent.OutputObject>;
      TierUpgraded: TypedContractEvent<TierUpgradedEvent.InputTuple, TierUpgradedEvent.OutputTuple, TierUpgradedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'Unstaked(address,uint256)': TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
      Unstaked: TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
    
    };
  }