/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FCMTaskMarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "LISTING_ROLE" | "auctionTasks" | "cancelSpotTask" | "claimAuctionRefund" | "escrowedBids" | "fcmToken" | "getAuctionPrice" | "getRoleAdmin" | "grantRole" | "hasRole" | "listAuctionTask" | "listSpotTask" | "placeBid" | "registry" | "renounceRole" | "revokeRole" | "settleAuction" | "spotTaskAmounts" | "spotTaskCancelled" | "spotTaskListers" | "supportsInterface"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionListed" | "AuctionSettled" | "BidPlaced" | "BidRefunded" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "SpotTaskCancelled" | "SpotTaskListed"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'LISTING_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'auctionTasks', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'cancelSpotTask', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'claimAuctionRefund', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'escrowedBids', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'fcmToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAuctionPrice', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'listAuctionTask', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'listSpotTask', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'placeBid', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'settleAuction', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'spotTaskAmounts', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'spotTaskCancelled', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'spotTaskListers', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LISTING_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctionTasks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelSpotTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimAuctionRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowedBids', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fcmToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuctionPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listAuctionTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listSpotTask', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'spotTaskAmounts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'spotTaskCancelled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'spotTaskListers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
  }

  
    export namespace AuctionListedEvent {
      export type InputTuple = [taskId: BytesLike, lister: AddressLike, minPrice: BigNumberish, maxPrice: BigNumberish, duration: BigNumberish];
      export type OutputTuple = [taskId: string, lister: string, minPrice: bigint, maxPrice: bigint, duration: bigint];
      export interface OutputObject {taskId: string, lister: string, minPrice: bigint, maxPrice: bigint, duration: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionSettledEvent {
      export type InputTuple = [taskId: BytesLike, winningAgent: BytesLike, price: BigNumberish];
      export type OutputTuple = [taskId: string, winningAgent: string, price: bigint];
      export interface OutputObject {taskId: string, winningAgent: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidPlacedEvent {
      export type InputTuple = [taskId: BytesLike, agentDid: BytesLike, price: BigNumberish];
      export type OutputTuple = [taskId: string, agentDid: string, price: bigint];
      export interface OutputObject {taskId: string, agentDid: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidRefundedEvent {
      export type InputTuple = [taskId: BytesLike, agent: AddressLike, amount: BigNumberish];
      export type OutputTuple = [taskId: string, agent: string, amount: bigint];
      export interface OutputObject {taskId: string, agent: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SpotTaskCancelledEvent {
      export type InputTuple = [taskId: BytesLike, lister: AddressLike, refund: BigNumberish];
      export type OutputTuple = [taskId: string, lister: string, refund: bigint];
      export interface OutputObject {taskId: string, lister: string, refund: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SpotTaskListedEvent {
      export type InputTuple = [taskId: BytesLike, lister: AddressLike, maxPrice: BigNumberish, priority: BigNumberish];
      export type OutputTuple = [taskId: string, lister: string, maxPrice: bigint, priority: bigint];
      export interface OutputObject {taskId: string, lister: string, maxPrice: bigint, priority: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FCMTaskMarketplace extends BaseContract {
    
    connect(runner?: ContractRunner | null): FCMTaskMarketplace;
    waitForDeployment(): Promise<this>;

    interface: FCMTaskMarketplaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    LISTING_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    auctionTasks: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, bigint, bigint, bigint, boolean, string] & {taskId: string, minPrice: bigint, maxPrice: bigint, auctionEnd: bigint, auctionDuration: bigint, settled: boolean, lister: string }],
      'view'
    >
    

    
    cancelSpotTask: TypedContractMethod<
      [_taskId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    claimAuctionRefund: TypedContractMethod<
      [_taskId: BytesLike, _bidIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    escrowedBids: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    fcmToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAuctionPrice: TypedContractMethod<
      [_taskId: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    listAuctionTask: TypedContractMethod<
      [_taskId: BytesLike, _minPrice: BigNumberish, _maxPrice: BigNumberish, _auctionDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    listSpotTask: TypedContractMethod<
      [_taskId: BytesLike, _maxPrice: BigNumberish, _deadline: BigNumberish, _priority: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    placeBid: TypedContractMethod<
      [_taskId: BytesLike, _agentDid: BytesLike, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    settleAuction: TypedContractMethod<
      [_taskId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    spotTaskAmounts: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    spotTaskCancelled: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    spotTaskListers: TypedContractMethod<
      [arg0: BytesLike, ],
      [string],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'LISTING_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'auctionTasks'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, bigint, bigint, bigint, boolean, string] & {taskId: string, minPrice: bigint, maxPrice: bigint, auctionEnd: bigint, auctionDuration: bigint, settled: boolean, lister: string }],
      'view'
    >;
getFunction(nameOrSignature: 'cancelSpotTask'): TypedContractMethod<
      [_taskId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimAuctionRefund'): TypedContractMethod<
      [_taskId: BytesLike, _bidIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrowedBids'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fcmToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAuctionPrice'): TypedContractMethod<
      [_taskId: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'listAuctionTask'): TypedContractMethod<
      [_taskId: BytesLike, _minPrice: BigNumberish, _maxPrice: BigNumberish, _auctionDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'listSpotTask'): TypedContractMethod<
      [_taskId: BytesLike, _maxPrice: BigNumberish, _deadline: BigNumberish, _priority: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'placeBid'): TypedContractMethod<
      [_taskId: BytesLike, _agentDid: BytesLike, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settleAuction'): TypedContractMethod<
      [_taskId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'spotTaskAmounts'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'spotTaskCancelled'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'spotTaskListers'): TypedContractMethod<
      [arg0: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'AuctionListed'): TypedContractEvent<AuctionListedEvent.InputTuple, AuctionListedEvent.OutputTuple, AuctionListedEvent.OutputObject>;
getEvent(key: 'AuctionSettled'): TypedContractEvent<AuctionSettledEvent.InputTuple, AuctionSettledEvent.OutputTuple, AuctionSettledEvent.OutputObject>;
getEvent(key: 'BidPlaced'): TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
getEvent(key: 'BidRefunded'): TypedContractEvent<BidRefundedEvent.InputTuple, BidRefundedEvent.OutputTuple, BidRefundedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'SpotTaskCancelled'): TypedContractEvent<SpotTaskCancelledEvent.InputTuple, SpotTaskCancelledEvent.OutputTuple, SpotTaskCancelledEvent.OutputObject>;
getEvent(key: 'SpotTaskListed'): TypedContractEvent<SpotTaskListedEvent.InputTuple, SpotTaskListedEvent.OutputTuple, SpotTaskListedEvent.OutputObject>;

    filters: {
      
      'AuctionListed(bytes32,address,uint256,uint256,uint256)': TypedContractEvent<AuctionListedEvent.InputTuple, AuctionListedEvent.OutputTuple, AuctionListedEvent.OutputObject>;
      AuctionListed: TypedContractEvent<AuctionListedEvent.InputTuple, AuctionListedEvent.OutputTuple, AuctionListedEvent.OutputObject>;
    

      'AuctionSettled(bytes32,bytes32,uint256)': TypedContractEvent<AuctionSettledEvent.InputTuple, AuctionSettledEvent.OutputTuple, AuctionSettledEvent.OutputObject>;
      AuctionSettled: TypedContractEvent<AuctionSettledEvent.InputTuple, AuctionSettledEvent.OutputTuple, AuctionSettledEvent.OutputObject>;
    

      'BidPlaced(bytes32,bytes32,uint256)': TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
      BidPlaced: TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
    

      'BidRefunded(bytes32,address,uint256)': TypedContractEvent<BidRefundedEvent.InputTuple, BidRefundedEvent.OutputTuple, BidRefundedEvent.OutputObject>;
      BidRefunded: TypedContractEvent<BidRefundedEvent.InputTuple, BidRefundedEvent.OutputTuple, BidRefundedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'SpotTaskCancelled(bytes32,address,uint256)': TypedContractEvent<SpotTaskCancelledEvent.InputTuple, SpotTaskCancelledEvent.OutputTuple, SpotTaskCancelledEvent.OutputObject>;
      SpotTaskCancelled: TypedContractEvent<SpotTaskCancelledEvent.InputTuple, SpotTaskCancelledEvent.OutputTuple, SpotTaskCancelledEvent.OutputObject>;
    

      'SpotTaskListed(bytes32,address,uint256,uint8)': TypedContractEvent<SpotTaskListedEvent.InputTuple, SpotTaskListedEvent.OutputTuple, SpotTaskListedEvent.OutputObject>;
      SpotTaskListed: TypedContractEvent<SpotTaskListedEvent.InputTuple, SpotTaskListedEvent.OutputTuple, SpotTaskListedEvent.OutputObject>;
    
    };
  }