/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'FCMAgentRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FCMAgentRegistry__factory>
getContractFactory(name: 'FCMEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FCMEscrow__factory>
getContractFactory(name: 'FCMGovernance', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FCMGovernance__factory>
getContractFactory(name: 'ITierStaking', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITierStaking__factory>
getContractFactory(name: 'FCMReputationNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FCMReputationNFT__factory>
getContractFactory(name: 'FCMRewardsPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FCMRewardsPool__factory>
getContractFactory(name: 'ITierStaking', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITierStaking__factory>
getContractFactory(name: 'FCMTaskMarketplace', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FCMTaskMarketplace__factory>
getContractFactory(name: 'FCMTierStaking', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FCMTierStaking__factory>
getContractFactory(name: 'FCMToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FCMToken__factory>

  getContractAt(name: 'FCMAgentRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FCMAgentRegistry>
getContractAt(name: 'FCMEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FCMEscrow>
getContractAt(name: 'FCMGovernance', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FCMGovernance>
getContractAt(name: 'ITierStaking', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITierStaking>
getContractAt(name: 'FCMReputationNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FCMReputationNFT>
getContractAt(name: 'FCMRewardsPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FCMRewardsPool>
getContractAt(name: 'ITierStaking', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITierStaking>
getContractAt(name: 'FCMTaskMarketplace', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FCMTaskMarketplace>
getContractAt(name: 'FCMTierStaking', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FCMTierStaking>
getContractAt(name: 'FCMToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FCMToken>

  deployContract(name: 'FCMAgentRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMAgentRegistry>
deployContract(name: 'FCMEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMEscrow>
deployContract(name: 'FCMGovernance', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMGovernance>
deployContract(name: 'ITierStaking', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITierStaking>
deployContract(name: 'FCMReputationNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMReputationNFT>
deployContract(name: 'FCMRewardsPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMRewardsPool>
deployContract(name: 'ITierStaking', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITierStaking>
deployContract(name: 'FCMTaskMarketplace', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMTaskMarketplace>
deployContract(name: 'FCMTierStaking', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMTierStaking>
deployContract(name: 'FCMToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMToken>

  deployContract(name: 'FCMAgentRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMAgentRegistry>
deployContract(name: 'FCMEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMEscrow>
deployContract(name: 'FCMGovernance', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMGovernance>
deployContract(name: 'ITierStaking', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITierStaking>
deployContract(name: 'FCMReputationNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMReputationNFT>
deployContract(name: 'FCMRewardsPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMRewardsPool>
deployContract(name: 'ITierStaking', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITierStaking>
deployContract(name: 'FCMTaskMarketplace', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMTaskMarketplace>
deployContract(name: 'FCMTierStaking', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMTierStaking>
deployContract(name: 'FCMToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FCMToken>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  