/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FCMGovernance } from './FCMGovernance.js';
export type { ITierStaking } from './ITierStaking.js';