/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface FCMRewardsPoolInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_ROLE" | "DEFAULT_ADMIN_ROLE" | "EPOCH_DURATION" | "ORACLE_ROLE" | "agentRewards" | "claimRewards" | "currentEpoch" | "emergencyWithdraw" | "epochStartTime" | "epochs" | "fcmToken" | "finalizeEpoch" | "fundEpoch" | "getAgentLifetimeEarnings" | "getAgentPendingRewards" | "getEffectivePrice" | "getEpochInfo" | "getRoleAdmin" | "grantRole" | "hasRole" | "minClaimAmount" | "paused" | "recordWork" | "renounceRole" | "revokeRole" | "setMinClaimAmount" | "setTaskPrice" | "supportsInterface" | "taskPrices" | "tierStaking" | "totalPoolBalance"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EpochFinalized" | "EpochFunded" | "Paused" | "RewardsClaimed" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "TaskPriceUpdated" | "Unpaused" | "WorkRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'EPOCH_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'ORACLE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'agentRewards', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claimRewards', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentEpoch', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'epochStartTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'epochs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fcmToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalizeEpoch', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundEpoch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgentLifetimeEarnings', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAgentPendingRewards', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getEffectivePrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEpochInfo', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'minClaimAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordWork', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setMinClaimAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTaskPrice', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'taskPrices', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tierStaking', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalPoolBalance', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'EPOCH_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ORACLE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agentRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochStartTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'epochs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fcmToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentLifetimeEarnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentPendingRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEffectivePrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEpochInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minClaimAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordWork', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinClaimAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTaskPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'taskPrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tierStaking', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalPoolBalance', data: BytesLike): Result;
  }

  
    export namespace EpochFinalizedEvent {
      export type InputTuple = [epoch: BigNumberish, totalDistributed: BigNumberish];
      export type OutputTuple = [epoch: bigint, totalDistributed: bigint];
      export interface OutputObject {epoch: bigint, totalDistributed: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EpochFundedEvent {
      export type InputTuple = [epoch: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [epoch: bigint, amount: bigint];
      export interface OutputObject {epoch: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardsClaimedEvent {
      export type InputTuple = [agent: AddressLike, amount: BigNumberish, epoch: BigNumberish];
      export type OutputTuple = [agent: string, amount: bigint, epoch: bigint];
      export interface OutputObject {agent: string, amount: bigint, epoch: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaskPriceUpdatedEvent {
      export type InputTuple = [agentType: BigNumberish, basePrice: BigNumberish, marketMultiplier: BigNumberish];
      export type OutputTuple = [agentType: bigint, basePrice: bigint, marketMultiplier: bigint];
      export interface OutputObject {agentType: bigint, basePrice: bigint, marketMultiplier: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkRecordedEvent {
      export type InputTuple = [agent: AddressLike, agentType: BigNumberish, workUnits: BigNumberish];
      export type OutputTuple = [agent: string, agentType: bigint, workUnits: bigint];
      export interface OutputObject {agent: string, agentType: bigint, workUnits: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FCMRewardsPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): FCMRewardsPool;
    waitForDeployment(): Promise<this>;

    interface: FCMRewardsPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    EPOCH_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ORACLE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    agentRewards: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {totalEarned: bigint, epochWork: bigint, epochClaimed: bigint, lastClaimEpoch: bigint, consecutiveEpochs: bigint }],
      'view'
    >
    

    
    claimRewards: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    currentEpoch: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    epochStartTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    epochs: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, boolean] & {totalPool: bigint, totalDistributed: bigint, tasksCompleted: bigint, finalized: boolean }],
      'view'
    >
    

    
    fcmToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    finalizeEpoch: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    fundEpoch: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAgentLifetimeEarnings: TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getAgentPendingRewards: TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getEffectivePrice: TypedContractMethod<
      [agentType: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getEpochInfo: TypedContractMethod<
      [epochNum: BigNumberish, ],
      [[bigint, bigint, bigint, boolean] & {totalPool: bigint, totalDistributed: bigint, tasksCompleted: bigint, finalized: boolean }],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    minClaimAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    recordWork: TypedContractMethod<
      [agent: AddressLike, agentType: BigNumberish, workUnits: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMinClaimAmount: TypedContractMethod<
      [_min: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTaskPrice: TypedContractMethod<
      [agentType: BigNumberish, basePrice: BigNumberish, marketMultiplier: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    taskPrices: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, boolean] & {basePrice: bigint, marketMultiplier: bigint, active: boolean }],
      'view'
    >
    

    
    tierStaking: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalPoolBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'EPOCH_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ORACLE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'agentRewards'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {totalEarned: bigint, epochWork: bigint, epochClaimed: bigint, lastClaimEpoch: bigint, consecutiveEpochs: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'claimRewards'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'currentEpoch'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'epochStartTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'epochs'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, boolean] & {totalPool: bigint, totalDistributed: bigint, tasksCompleted: bigint, finalized: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'fcmToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'finalizeEpoch'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundEpoch'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAgentLifetimeEarnings'): TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentPendingRewards'): TypedContractMethod<
      [agent: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getEffectivePrice'): TypedContractMethod<
      [agentType: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getEpochInfo'): TypedContractMethod<
      [epochNum: BigNumberish, ],
      [[bigint, bigint, bigint, boolean] & {totalPool: bigint, totalDistributed: bigint, tasksCompleted: bigint, finalized: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'minClaimAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recordWork'): TypedContractMethod<
      [agent: AddressLike, agentType: BigNumberish, workUnits: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinClaimAmount'): TypedContractMethod<
      [_min: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTaskPrice'): TypedContractMethod<
      [agentType: BigNumberish, basePrice: BigNumberish, marketMultiplier: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'taskPrices'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, boolean] & {basePrice: bigint, marketMultiplier: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'tierStaking'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalPoolBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'EpochFinalized'): TypedContractEvent<EpochFinalizedEvent.InputTuple, EpochFinalizedEvent.OutputTuple, EpochFinalizedEvent.OutputObject>;
getEvent(key: 'EpochFunded'): TypedContractEvent<EpochFundedEvent.InputTuple, EpochFundedEvent.OutputTuple, EpochFundedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RewardsClaimed'): TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'TaskPriceUpdated'): TypedContractEvent<TaskPriceUpdatedEvent.InputTuple, TaskPriceUpdatedEvent.OutputTuple, TaskPriceUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'WorkRecorded'): TypedContractEvent<WorkRecordedEvent.InputTuple, WorkRecordedEvent.OutputTuple, WorkRecordedEvent.OutputObject>;

    filters: {
      
      'EpochFinalized(uint256,uint256)': TypedContractEvent<EpochFinalizedEvent.InputTuple, EpochFinalizedEvent.OutputTuple, EpochFinalizedEvent.OutputObject>;
      EpochFinalized: TypedContractEvent<EpochFinalizedEvent.InputTuple, EpochFinalizedEvent.OutputTuple, EpochFinalizedEvent.OutputObject>;
    

      'EpochFunded(uint256,uint256)': TypedContractEvent<EpochFundedEvent.InputTuple, EpochFundedEvent.OutputTuple, EpochFundedEvent.OutputObject>;
      EpochFunded: TypedContractEvent<EpochFundedEvent.InputTuple, EpochFundedEvent.OutputTuple, EpochFundedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RewardsClaimed(address,uint256,uint256)': TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
      RewardsClaimed: TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'TaskPriceUpdated(uint8,uint256,uint256)': TypedContractEvent<TaskPriceUpdatedEvent.InputTuple, TaskPriceUpdatedEvent.OutputTuple, TaskPriceUpdatedEvent.OutputObject>;
      TaskPriceUpdated: TypedContractEvent<TaskPriceUpdatedEvent.InputTuple, TaskPriceUpdatedEvent.OutputTuple, TaskPriceUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'WorkRecorded(address,uint8,uint256)': TypedContractEvent<WorkRecordedEvent.InputTuple, WorkRecordedEvent.OutputTuple, WorkRecordedEvent.OutputObject>;
      WorkRecorded: TypedContractEvent<WorkRecordedEvent.InputTuple, WorkRecordedEvent.OutputTuple, WorkRecordedEvent.OutputObject>;
    
    };
  }