/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FCMRewardsPool } from './FCMRewardsPool.js';
export type { ITierStaking } from './ITierStaking.js';