/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ITierStakingInterface extends Interface {
    getFunction(nameOrSignature: "getEffectiveMultiplier" | "getMaxConcurrent" | "getTier"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getEffectiveMultiplier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMaxConcurrent', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTier', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getEffectiveMultiplier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMaxConcurrent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTier', data: BytesLike): Result;
  }

  

  export interface ITierStaking extends BaseContract {
    
    connect(runner?: ContractRunner | null): ITierStaking;
    waitForDeployment(): Promise<this>;

    interface: ITierStakingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getEffectiveMultiplier: TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getMaxConcurrent: TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getTier: TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getEffectiveMultiplier'): TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMaxConcurrent'): TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTier'): TypedContractMethod<
      [operator: AddressLike, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }